### ISSUE TITLE
Navbar active tab issue

### ISSUE THREAD

**Issue by QuentinBouygues** [awi2017-option1group1/Prello-front#38]
On the navbar, independantly of the page selected, I always see the two left tabs as active.

<img width="354" alt="screen shot 2017-11-06 at 21 15 02" src="https://user-images.githubusercontent.com/14580140/32461898-bc99ca14-c337-11e7-822e-83e2440921c2.png">

**Acceptance criteria of the fix** : the only active tab is the one corresponding to the page I'm on.

**Comment by Porquepix** [comment]
Yes the active state have lot of bugs. I think (if I have time) I will remove that.
